/**
 * API Module - Loads pre-computed data from static JSON files
 * All data is pre-generated by scripts/generate_data.py
 * Detail files are gzip-compressed for ~90% size reduction
 */

const API = (() => {
    const DATA_PATH = 'data';
    const FORGEJO_BASE = 'https://git.tricoteuses.fr/codes';
    const cache = new Map();

    async function loadJson(path) {
        const cached = cache.get(path);
        if (cached) return cached;

        const response = await fetch(`${DATA_PATH}/${path}`);
        if (!response.ok) {
            throw new Error(`Failed to load ${path}: ${response.status}`);
        }
        const data = await response.json();
        cache.set(path, data);
        return data;
    }

    async function loadGzipJson(path) {
        const cached = cache.get(path);
        if (cached) return cached;

        const response = await fetch(`${DATA_PATH}/${path}`);
        if (!response.ok) {
            throw new Error(`Failed to load ${path}: ${response.status}`);
        }

        // Decompress gzip using DecompressionStream (modern browsers)
        const ds = new DecompressionStream('gzip');
        const decompressedStream = response.body.pipeThrough(ds);
        const text = await new Response(decompressedStream).text();
        const data = JSON.parse(text);
        cache.set(path, data);
        return data;
    }

    async function fetchRepositories() {
        return loadJson('repos.json');
    }

    async function fetchCommits(repoName, since, until) {
        const commits = await loadJson(`commits/${repoName}.json`);

        // Filter by date range
        return commits.filter(c => {
            if (since && c.date < since) return false;
            if (until && c.date > until) return false;
            return true;
        });
    }

    async function fetchCommitDetail(repoName, sha) {
        // Check cache first
        const cacheKey = `detail:${repoName}:${sha}`;
        const cached = cache.get(cacheKey);
        if (cached) return cached;

        // Load pre-computed detail from gzip-compressed JSON
        const shortSha = sha.substring(0, 12);

        try {
            const detail = await loadGzipJson(`details/${repoName}/${shortSha}.json.gz`);

            // Add external URL for reference
            const fullSha = detail.fullSha || sha;
            detail.externalUrl = `${FORGEJO_BASE}/${repoName}/commit/${fullSha}`;

            cache.set(cacheKey, detail);
            return detail;
        } catch (err) {
            throw new Error(`Commit ${sha} not found: ${err.message}`);
        }
    }

    function formatCodeName(name) {
        const display = name.replace(/_/g, ' ');
        return display.charAt(0).toUpperCase() + display.slice(1);
    }

    return {
        fetchRepositories,
        fetchCommits,
        fetchCommitDetail,
        formatCodeName
    };
})();
