/**
 * API Module - Loads pre-computed static JSON data
 * All data is generated by scripts/generate_data.py
 */

const API = (() => {
    const DATA_PATH = 'data';
    const cache = new Map();

    async function loadJson(path) {
        const cached = cache.get(path);
        if (cached) return cached;

        const response = await fetch(`${DATA_PATH}/${path}`);
        if (!response.ok) {
            throw new Error(`Failed to load ${path}: ${response.status}`);
        }
        const data = await response.json();
        cache.set(path, data);
        return data;
    }

    async function fetchRepositories() {
        return loadJson('repos.json');
    }

    async function fetchCommits(repoName, since, until) {
        const commits = await loadJson(`commits/${repoName}.json`);

        // Filter by date range
        return commits.filter(c => {
            if (since && c.date < since) return false;
            if (until && c.date > until) return false;
            return true;
        });
    }

    async function fetchCommitDetail(repoName, sha) {
        const shortSha = sha.substring(0, 12);
        return loadJson(`details/${repoName}/${shortSha}.json`);
    }

    function formatCodeName(name) {
        const display = name.replace(/_/g, ' ');
        return display.charAt(0).toUpperCase() + display.slice(1);
    }

    return {
        fetchRepositories,
        fetchCommits,
        fetchCommitDetail,
        formatCodeName
    };
})();
